#delete all test data files, if some of these don't exist and fail that's okay
rm BasicInputFile.txt
rm BasicOutputFile.txt
rm MediumInputFileClient2.txt
rm MediumInputFileClient3.txt
rm MediumOutputFileClient1FirstGet.txt
rm MediumOutputFileClient1SecondGet.txt
rm MediumOutputFileClient1ThirdGet.txt
rm MediumOutputFileClient1FourthGet.txt
rm MediumOutputFileClient2FirstGet.txt
rm MediumOutputFileClient2SecondGet.txt
rm MediumOutputFileClient2ThirdGet.txt
rm MediumOutputFileClient2FourthGet.txt
rm MediumOutputFileClient3FirstGet.txt
rm MediumOutputFileClient3SecondGet.txt
rm MediumOutputFileClient3ThirdGet.txt
rm MediumOutputFileClient3FourthGet.txt
rm GiantInputFile.txt
rm GiantOutputFile.txt