#!./expect -f 

#PREREQUISITES AND ASSUMPTIONS:
#all testing is done through putty
#there is already a server started manually in another putty instance
#command to start server is "./server" from the build folder
#server and client are both on the same CCCWORK machine

#SUCCESS CRITERIA:
#server shows command from client
#client shows put command with no error related to put

#start the client
spawn ./../build/client localhost

#remove existing data
#this may throw a read failed error if there is no existing data
#this is expected, we're just cleaning up what we intend to use
expect ">" {send "remove\r"}
expect "Please enter key to remove data:" {send "1\r"}

#put new data into index 1
expect ">" {send "put\r"}
expect "Please enter key to store data:" {send "1\r"}
expect "Do you want to send a file" {send "n\r"}
expect "Please enter the data to store:" {send "TC1\r"}

interact