#!./expect -f 

#PREREQUISITES AND ASSUMPTIONS:
#all testing is done through putty
#there is already a server started manually in another putty instance
#command to start server is "./server" from the build folder
# (*important*) server and client are both on the same CCCWORK machine

#SUCCESS CRITERIA:
#server shows commands from client
#client shows a working put, a working get (returns "TC5"), a working remove, a get that does not return data, and then finally a failed remove

#start the client
spawn ./../build/client localhost

#remove existing data
#this may throw a read failed error if there is no existing data
#this is expected, we're just cleaning up what we intend to use
expect ">" {send "remove\r"}
expect "Please enter key to remove data:" {send "5\r"}

#put new data into index 5
expect ">" {send "put\r"}
expect "Please enter key to store data:" {send "5\r"}
expect "Do you want to send a file" {send "n\r"}
expect "Please enter the data to store:" {send "TC5\r"}

#now get data from index 5
expect ">" {send "get\r"}
expect "Please enter key to retrieve data:" {send "5\r"}
expect "Do you want to store data in a file" {send "n\r"}

#remove data we just got
expect ">" {send "remove\r"}
expect "Please enter key to remove data:" {send "5\r"}

#get data from index 5 again, this should fail
expect ">" {send "get\r"}
expect "Please enter key to retrieve data:" {send "5\r"}
expect "Do you want to store data in a file" {send "n\r"}

#remove data that does not exist, this should fail
expect ">" {send "remove\r"}
expect "Please enter key to remove data:" {send "5\r"}

#return to user control
interact